spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/edutrack
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: COLOCA_AQUI_O_CLIENT_SECRET_DO_KEYCLOAK
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/edutrack

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO
