# Arquivo: config-repo/api-gateway.yml (VERSÃO ATUALIZADA)

spring:
  application:
    name: api-gateway

  # A seção 'config' geralmente fica no bootstrap.yml, mas se estiver aqui,
  # não há problema. O importante é que funcione.
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8081/realms/edutrack}
            jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

  # Configuração de Rastreamento (Zipkin)
  zipkin:
    base-url: http://zipkin:9411/


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8080

# Configurações do Actuator, Métricas e Tracing
management:
  # <<< ADICIONADO: Para mostrar detalhes no health check
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0 # Rastreia 100% das requisições

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO