spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

    # Configuração de Rotas do Gateway
    gateway:
      default-filters:
        - TokenRelay # Repassa o token JWT para todos os microserviços automaticamente
      routes:
        # Rota para o Identity Service
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
          filters:
            - RewritePath=/identity/(?<segment>.*), /$\{segment}

        # Rota para o Student Service
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - RewritePath=/student/(?<segment>.*), /$\{segment}

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8081/realms/edutrack}
            jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

# ================================
# ZIPKIN (Micrometer + Spring Boot 3)
# ================================
management:
  zipkin:
    tracing:
      endpoint: http://edutrack-zipkin:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG # Ativado DEBUG para facilitar diagnóstico