server:
  port: 8080

spring:
  cloud:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8081/realms/edutrack}
            jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  zipkin:
    tracing:
      endpoint: http://edutrack-zipkin:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
