server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:
  cloud:
    config:
      uri: http://config-server:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
