spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

    gateway:
      routes:
        - id: edutrack-core-v1
          uri: lb://EDUTRACK-CORE
          predicates:
            - Path=/api/v1/**
    
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8081/realms/edutrack}
            jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

# --- OBSERVABILIDADE ---
management:
  zipkin:
    tracing:
      endpoint: http://edutrack-zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# --- SERVICE DISCOVERY ---
eureka:
  client:
    serviceUrl:
      defaultZone: http://edutrack-eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8080

# --- LOGS ---
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    # Adicionei para monitorar a resolução de rotas especificamente
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
