spring:
  application:
    name: api-gateway

  # ================================
  # CONFIG SERVER (método moderno em vez de bootstrap.yml)
  # ================================
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

    # ================================
    # GATEWAY DISCOVERY (via Eureka)
    # ================================
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    # ================================
    # KEYCLOAK / OAUTH2 JWT
    # ================================
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8081/realms/edutrack}
            jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs


# ================================
# ZIPKIN (Micrometer)
# ================================
management:
  zipkin:
    tracing:
      endpoint: http://edutrack-zipkin:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"


# ================================
# EUREKA CLIENT
# ================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true


# ================================
# SERVER CONFIG
# ================================
server:
  port: 8080


# ================================
# LOGGING
# ================================
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
