server:
  port: 8083

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://postgres-db:5432/edutrack_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/edutrack
          jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

keycloak:
  admin-client:
    server-url: http://keycloak:8081
    realm: edutrack
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:identity-service}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
