# Arquivo: config-repo/identity-service.yml (VERSÃO ATUALIZADA)

spring:
  application:
    name: identity-service

  # A seção 'config' geralmente fica no bootstrap.yml, mas se estiver aqui,
  # não há problema. O importante é que funcione.
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

  datasource:
    url: jdbc:postgresql://postgres-db:5432/edutrack_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8_81/realms/edutrack}
          jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

  # ===============================================================
  # ADIÇÃO: Configuração de Rastreamento (Zipkin)
  # ===============================================================
  zipkin:
    base-url: http://zipkin:9411/


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8083

# ===============================================================
# ADIÇÃO: Configurações do Actuator e Métricas (Prometheus)
# ===============================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0