spring:
  application:
    name: identity-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 10000
      import-check:
        enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/edutrack_identity
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.config: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
