server:
  port: 8083

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://edutrack-keycloak-db:5432/edutrack_db # Ajustado para o nome do container do banco
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Deve bater exatamente com o que o Gateway envia
          issuer-uri: http://keycloak:8081/realms/edutrack
          jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: edutrack-kafka:9092 # Verifique se a porta interna é 9092 ou 29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topics:
      user-created: user.created

keycloak:
  admin-client:
    server-url: http://keycloak:8081
    realm: edutrack
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:identity-service}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://edutrack-eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  
  # CORREÇÃO DO ZIPKIN AQUI:
  zipkin:
    tracing:
      endpoint: http://edutrack-zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG # IMPORTANTE: Para ver por que o 401 acontece
    com.educ.identityservice: DEBUG