server:
  port: 8083

spring:
  application:
    name: identity-service
  config:
    import: optional:configserver:
  cloud:
    config:
      uri: http://config-server:8888
  datasource:
    url: jdbc:postgresql://postgres-db:5432/edutrack_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
