server:
  port: 8084

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:postgresql://student-db:5432/student_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: edutrack-kafka:29092
    consumer:
      group-id: student-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.educ.student_service.messaging.event"
        spring.json.use.type.headers: false

    topics:
      user-created: identity.user.created

  data:
    redis:
      password: EDtrack@2025!
      timeout: 2000ms
      cluster:
        nodes:
          - redis-node-1:6379
          - redis-node-2:6379
          - redis-node-3:6379
          - redis-node-4:6379
          - redis-node-5:6379
          - redis-node-6:6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/edutrack
          jwk-set-uri: http://keycloak:8081/realms/edutrack/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.educ.student_service: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.redis: INFO
